/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WorkspaceFileListResult, WorkspaceFileOpenResult, WorkspaceFileReadResult, WorkspaceFileRevealResult, WorkspaceFileStatResult, WorkspaceFileWriteResult } from '@deepseek-ai/dsh-host-workspace-files/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b737061636546696c6573 {
    list: (path?: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileListResult>>
    open: (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileOpenResult>>
    read: (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileReadResult>>
    reveal: (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileRevealResult>>
    stat: (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileStatResult>>
    write: (path: string, content: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileWriteResult>>
  }
  interface TypertRemoteMap {
    'workspaceFiles/list': (path?: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileListResult>>
    'workspaceFiles/open': (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileOpenResult>>
    'workspaceFiles/read': (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileReadResult>>
    'workspaceFiles/reveal': (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileRevealResult>>
    'workspaceFiles/stat': (path: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileStatResult>>
    'workspaceFiles/write': (path: string, content: string, signal?: AbortSignal) => Promise<RemoteResult<WorkspaceFileWriteResult>>
  }
  interface TypertRemoteNamespaceMap {
    'workspaceFiles': TypertRemoteNamespace$776f726b737061636546696c6573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
